// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	chat "github.com/guil95/chat-go/internal/chat"

	mock "github.com/stretchr/testify/mock"
)

// ChatRepository is an autogenerated mock type for the ChatRepository type
type ChatRepository struct {
	mock.Mock
}

// SaveChat provides a mock function with given fields: ctx, _a1
func (_m *ChatRepository) SaveChat(ctx context.Context, _a1 chat.Chat) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.Chat) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewChatRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewChatRepository creates a new instance of ChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChatRepository(t mockConstructorTestingTNewChatRepository) *ChatRepository {
	mock := &ChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
